apiVersion: v1
kind: Service
metadata:
  name: sonatype-service
spec:
  type: LoadBalancer
  ports:
    - name: sonatype-registry
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: sonatype-registry
